import { useRef, useState } from 'react'
import { Button, ChoiceGroup, EvidenceBadge, StepIndicator, type EvidenceState } from './components'
import './design-system.css'

const siteOptions = [
  {value:'building',label:'A building is present'},
  {value:'partial',label:'A building has been partly removed'},
  {value:'empty',label:'The site appears empty',description:'An observation, not a legal-use classification'},
  {value:'unknown',label:'I do not know'},
]
const useOptions = [
  {value:'housing',label:'Housing only',description:'Unit count and attached/detached form are separate questions'},
  {value:'mixed',label:'Housing and another use',description:'Captured for review; outside the current rule coverage'},
  {value:'nonresidential',label:'Nonresidential',description:'Captured for review; outside the current rule coverage'},
  {value:'unknown',label:'I have not decided'},
]
const workOptions = [
  ['repair','Repair or remodel'],['addition','Build an addition'],['conversion','Convert interior space'],['partial','Partly demolish and rebuild'],['demolition','Demolish a building'],['new','Construct a new building'],['site','Excavate, grade or do site work'],['unsure','Other / not sure'],
]
const palette = [
  ['Pittsburgh gold','--color-gold','#FFB612'],['Black','--color-black','#000000'],['White','--color-white','#FFFFFF'],['Steel','--color-text-secondary','#53616B'],['Surface','--color-surface','#F1F2F2'],
]

export default function DesignSystem() {
  const [step,setStep] = useState(0)
  const [site,setSite] = useState('unknown')
  const [use,setUse] = useState('unknown')
  const [work,setWork] = useState<string[]>([])
  const [notice,setNotice] = useState('')
  const questionRef = useRef<HTMLDivElement>(null)
  const move = (next:number) => {setStep(next);setNotice('');requestAnimationFrame(()=>questionRef.current?.focus())}
  const currentLabel = (items:{value:string;label:string}[],value:string) => items.find(item=>item.value===value)?.label??value
  const unsupported = use==='mixed'||use==='nonresidential'||work.some(item=>!['repair','addition'].includes(item))
  return <div className="design-system"><header className="ds-page-header"><a href="/">Housing Navigator <span>Pittsburgh</span></a><span>Design system / v0.1</span></header><div className="ds-page-layout"><aside className="ds-sidebar"><strong>System contents</strong><nav aria-label="Design system sections"><a href="#walkthrough">Walkthrough preview</a><a href="#identity">Identity & tokens</a><a href="#evidence-states">Evidence states</a><a href="#controls">Controls</a><a href="#flow-contract">Flow & boundaries</a></nav><a className="ds-return" href="/">Open working prototype</a></aside><main className="ds-page-main"><div className="ds-page-intro"><h1>A property tool that asks the next useful question.</h1><p>Pittsburgh's black and gold, a parcel-centered workspace, and a guided intake that distinguishes records from assumptions.</p><div className="ds-preview-label">Design preview. This page does not run a property screen or make live requests.</div></div>
    <section id="walkthrough" className="ds-section"><div className="ds-section-heading"><h2>Try the question flow</h2><span>Four-screen interaction sample</span></div><p className="ds-description">This sample shows site condition, intended use and multiple work activities. The complete proposed intake also asks about current use, form, units and evidence.</p><div className="walkthrough-preview"><div className="preview-context"><div><strong>1623 Lanark St</strong><span>Fineview, City of Pittsburgh</span></div><EvidenceBadge state="snapshot"/></div><div className="preview-progress"><StepIndicator labels={['Site','Intended use','Work','Review']} current={step}/></div><div className="preview-conflict"><EvidenceBadge state="conflict"/><p>Assessment says vacant land; permits describe a dwelling. Your answers do not resolve this discrepancy.</p></div><div className="preview-question" tabIndex={-1} ref={questionRef}>
      {step===0&&<ChoiceGroup legend="What is on the site today?" hint="Describe what you know about the site, not what the assessment calls it." options={siteOptions} value={site} onChange={setSite}/>}
      {step===1&&<ChoiceGroup legend="What would the property be used for?" hint="Existing use, building form and number of homes are collected separately in the full intake." options={useOptions} value={use} onChange={setUse}/>}
      {step===2&&<fieldset className="ds-choice-group"><legend>What work are you considering?</legend><p className="ds-hint">Select all that apply. These choices describe intent; they do not establish rule coverage.</p><div className="ds-choice-list">{workOptions.map(([value,label])=><label key={value} className={`ds-choice ${work.includes(value)?'is-selected':''}`}><input type="checkbox" checked={work.includes(value)} onChange={e=>setWork(old=>e.target.checked?[...old,value]:old.filter(item=>item!==value))}/><span><strong>{label}</strong></span></label>)}</div></fieldset>}
      {step===3&&<div className="preview-review"><h2>Check your answers</h2><p className="ds-hint">These are your observations and proposed scope, not verified property facts.</p><dl>{[['Site condition',currentLabel(siteOptions,site),0],['Intended use',currentLabel(useOptions,use),1],['Work activities',work.length?workOptions.filter(([v])=>work.includes(v)).map(([,label])=>label).join(', '):'Not provided',2]].map(([label,value,number])=><div key={label}><dt>{label}</dt><dd>{value}</dd><Button variant="quiet" aria-label={`Change ${label}`} onClick={()=>move(Number(number))}>Change</Button></div>)}</dl><div className="preview-coverage"><strong>{unsupported?'Some choices are outside current rule coverage.':'The next step checks coverage and missing evidence.'}</strong><p>{unsupported?'Keep these answers in the brief and route to human review. Do not reuse the repair result.':'Housing plus repair or expansion still needs unit count, lawful-use evidence, form and precise scope before any conditional check.'}</p></div></div>}
    </div><div className="preview-actions">{step>0?<Button variant="secondary" onClick={()=>move(step-1)}>Back</Button>:<span/>}{step<3?<Button onClick={()=>move(step+1)}>Continue</Button>:<Button onClick={()=>setNotice('Preview complete. No screening was performed. Open the working prototype to use its narrower Lanark comparison.')}>Finish preview</Button>}</div>{notice&&<p className="preview-notice" role="status">{notice}</p>}</div></section>
    <section id="identity" className="ds-section"><h2>Identity & tokens</h2><p className="ds-description">Steelers-inspired black and gold, with an independent Pittsburgh 412 identity. Gold indicates selection and primary action, never legal approval.</p><div className="ds-palette">{palette.map(([name,token,hex])=><div key={token}><div className="ds-swatch" style={{background:`var(${token})`}}/><strong>{name}</strong><code>{hex}</code></div>)}</div><div className="ds-type-specimen"><div><span>IBM Plex Sans / questions & controls</span><h3>What would change on this property?</h3><p>One clear question. Plain-language options. Unknown is a valid answer.</p></div><div><span>IBM Plex Mono / identifiers</span><code>0023C00208000000</code><small>Preserve leading zeroes and source units.</small></div></div><p className="ds-description">Controls: 44px minimum height. Spacing: 4, 8, 12, 16, 24, 32px. Main body: 14px. Question: 26px. Control radius: 4px. Panel radius: 8px.</p></section>
    <section id="evidence-states" className="ds-section"><h2>Evidence states</h2><p className="ds-description">Freshness and rule outcome are separate. A live observation can still conflict with another source.</p><div className="ds-badge-examples">{(['live','snapshot','assumption','unknown','conflict','unavailable'] as EvidenceState[]).map(state=><EvidenceBadge key={state} state={state}/>)}</div><table className="ds-contract-table"><thead><tr><th>Situation</th><th>What the interface must do</th></tr></thead><tbody><tr><td>Live source fails</td><td>Name the failure and show the date of any retained snapshot.</td></tr><tr><td>Records disagree</td><td>Show both records and the next reconciliation action.</td></tr><tr><td>User selects a new category</td><td>Check coverage before selecting a rule pathway.</td></tr><tr><td>Not enough evidence</td><td>Return questions and next actions, not a green feasibility score.</td></tr></tbody></table></section>
    <section id="controls" className="ds-section"><h2>Controls</h2><p className="ds-description">One primary action per stage. Secondary actions preserve answers. Radio buttons choose one value; checkboxes capture work that can overlap.</p><div className="ds-control-examples"><Button onClick={()=>{document.getElementById('walkthrough')?.scrollIntoView();move(0)}}>Try the walkthrough</Button><Button variant="secondary" onClick={()=>{document.getElementById('identity')?.scrollIntoView()}}>View tokens</Button><Button disabled>Checking sources...</Button></div><div className="ds-field-example"><label>Existing homes <input type="number" min="0" step="1" placeholder="Unknown" aria-describedby="unknown-help"/></label><p id="unknown-help">Leave blank if unknown. Zero means no homes.</p></div></section>
    <section id="flow-contract" className="ds-section"><h2>Flow & boundaries</h2><ol className="ds-flow"><li>Confirm property and jurisdiction.</li><li>Capture the shared baseline once: observed condition, current use, form and existing homes.</li><li>Describe proposal A: intended use, activities, units, physical changes and ground disturbance.</li><li>Review answers, sources and coverage. Duplicate A to create B.</li><li>Change a scope, compare supported checks, and export the complete evidence trail.</li></ol><p className="ds-description">Implemented today: narrower Lanark comparison and one live assessment refresh. Proposed: full guided intake, wider coverage registry, parcel/permit/zoning/slope adapters and hosted API. Selecting a category in this preview does not implement those capabilities.</p></section>
  </main></div></div>
}
