import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true })
try {
  const page = await browser.newPage({ viewport: {width:1440,height:1000} })
  const errors = []
  page.on('pageerror', error=>errors.push(error.message))
  await page.goto('http://127.0.0.1:5173/')
  await page.getByRole('button',{name:'Use this demonstration property'}).click()
  await page.getByRole('heading',{name:'Your comparison',exact:true}).waitFor()
  const forms = page.locator('fieldset')
  await forms.nth(1).getByLabel('Proposed homes').fill('2')
  assert.match(await page.locator('.comparison-row').filter({hasText:'Rule pathway'}).innerText(),/added unit/i)
  await forms.nth(0).getByLabel('Lawful existing use').selectOption('yes')
  await forms.nth(0).getByLabel('Building form').selectOption('detached')
  await forms.nth(0).getByLabel('Land disturbance').selectOption('no')
  await forms.nth(0).getByLabel('Change in nonconformity').selectOption('same')
  assert.match(await page.locator('.conflict').innerText(),/VACANT LAND/)
  await forms.nth(0).getByLabel('Existing homes (assumed)').fill('-1')
  await page.getByRole('heading',{name:'Your comparison',exact:true}).waitFor()
  assert.match(await page.locator('.comparison-row').filter({has:page.getByRole('heading',{name:'Unit count input',exact:true})}).innerText(),/invalid/i)
  await forms.nth(0).getByLabel('Existing homes (assumed)').fill('1')
  await page.getByText('Check the latest assessment record',{exact:true}).click()
  await page.route('https://data.wprdc.org/**',route=>route.abort('failed'))
  await page.getByRole('button',{name:'Refresh assessment only'}).click()
  await page.getByText(/Live assessment unavailable at/).waitFor()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button',{name:'Download Markdown brief'}).click()
  const download = await downloadPromise
  await download.saveAs('/tmp/lanark-comparison-brief.md')
  const brief = await readFile('/tmp/lanark-comparison-brief.md','utf8')
  for (const text of ['0023C00208000000','VACANT LAND','lawful use: yes','proposed units: 2','https://ecode360.com','Live assessment unavailable','Financial feasibility']) assert.ok(brief.includes(text),`Brief missing ${text}`)
  await page.screenshot({path:'/tmp/lanark-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth),true,'Mobile horizontal overflow')
  await page.screenshot({path:'/tmp/lanark-mobile.png',fullPage:true})
  await page.unroute('https://data.wprdc.org/**')
  await page.getByRole('button',{name:'Refresh assessment only'}).click()
  await page.waitForFunction(()=>!document.querySelector('.refresh button').disabled,{},{timeout:16000})
  console.log('Actual live request:',await page.locator('.refresh-note').innerText())
  await page.emulateMedia({media:'print'})
  assert.equal(await page.locator('.refresh-note').isVisible(),true,'Print must retain refresh provenance')
  await page.pdf({path:'/tmp/lanark-print.pdf',format:'A4',printBackground:true})
  assert.deepEqual(errors,[])
  console.log('PASS: selection, proposal changes, persistent conflict, failed refresh, downloaded brief, mobile overflow, print rendering, no browser exceptions')
} finally { await browser.close() }
