import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true })
try {
  const page = await browser.newPage({ viewport: {width:1440,height:1000} })
  const errors = []
  page.on('pageerror', error=>errors.push(error.message))
  await page.goto(`${process.env.APP_ORIGIN ?? 'http://127.0.0.1:5173'}/prototype`)
  await page.evaluate(()=>document.fonts.ready)
  await page.getByLabel('Proposed homes').first().waitFor()
  assert.equal(await page.getByLabel('Proposed homes').count(),2,'Both proposal inputs must be present after the route loads')
  assert.equal(await page.getByLabel('Proposed homes').first().isVisible(),true)
  assert.equal(await page.getByRole('img',{name:'Pittsburgh 412, Steelers-inspired steelmark colors'}).isVisible(),true)
  await page.screenshot({path:'/tmp/lanark-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Compare proposals',exact:true}).click()
  assert.equal(await page.getByTestId('explanation-changes').locator('strong').innerText(),'1')
  assert.equal(await page.getByTestId('status-changes').locator('strong').innerText(),'0')
  assert.equal(await page.getByTestId('action-changes').locator('strong').innerText(),'0')
  assert.match(await page.locator('.decision-difference').innerText(),/next action is the same/)
  assert.match(await page.locator('.input-difference').innerText(),/Changed inputs: Type of work/)
  await page.getByRole('button',{name:'Try ground-disturbance contrast',exact:true}).click()
  assert.equal(await page.getByTestId('action-changes').locator('strong').innerText(),'1')
  assert.match(await page.locator('.input-difference').innerText(),/Changed inputs: Ground disturbance/)
  await page.getByRole('button',{name:'Edit proposals'}).click()
  await page.getByRole('button',{name:'Reset examples'}).click()
  const forms = page.locator('fieldset')
  await forms.nth(1).getByLabel('Proposed homes').fill('2')
  await forms.nth(0).getByLabel('Lawful existing use').selectOption('yes')
  await forms.nth(0).getByLabel('Building form').selectOption('detached')
  await forms.nth(0).getByLabel('Land disturbance').selectOption('no')
  await forms.nth(0).getByLabel('Change in nonconformity').selectOption('same')
  await page.getByRole('button',{name:'Compare proposals',exact:true}).click()
  const rule = page.locator('.comparison-row').filter({has:page.getByRole('heading',{name:'Rule pathway',exact:true})})
  await rule.locator('summary').click()
  assert.match(await rule.innerText(),/added unit/i)
  assert.match(await page.locator('.conflict').innerText(),/VACANT LAND/)
  await page.getByRole('button',{name:'Edit proposals'}).click()
  await forms.nth(0).getByLabel('Existing homes (assumed)').fill('-1')
  await page.getByRole('button',{name:'Compare proposals',exact:true}).click()
  const countRow = page.locator('.comparison-row').filter({has:page.getByRole('heading',{name:'Unit count input',exact:true})})
  await countRow.locator('summary').click()
  assert.match(await countRow.innerText(),/invalid/i)
  await page.getByRole('button',{name:'Edit proposals'}).click()
  await forms.nth(0).getByLabel('Existing homes (assumed)').fill('1')
  await page.getByRole('button',{name:'Evidence',exact:true}).click()
  await page.getByText('Check the latest assessment record',{exact:true}).click()
  await page.route('https://data.wprdc.org/**',route=>route.abort('failed'))
  await page.getByRole('button',{name:'Refresh assessment only'}).click()
  await page.getByText(/Live assessment unavailable at/).waitFor()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button',{name:'Export brief',exact:true}).click()
  const download = await downloadPromise
  await download.saveAs('/tmp/lanark-comparison-brief.md')
  const brief = await readFile('/tmp/lanark-comparison-brief.md','utf8')
  for (const text of ['0023C00208000000','VACANT LAND','lawful use: yes','proposed units: 2','https://ecode360.com','Live assessment unavailable','Financial feasibility']) assert.ok(brief.includes(text),`Brief missing ${text}`)
  await page.unroute('https://data.wprdc.org/**')
  await page.getByRole('button',{name:'Refresh assessment only'}).click()
  await page.waitForFunction(()=>!document.querySelector('.refresh button').disabled,{},{timeout:16000})
  console.log('Actual live request:',await page.locator('.refresh-note').innerText())
  await page.getByRole('button',{name:'Proposals',exact:true}).click()
  await page.getByRole('button',{name:'Reset examples'}).click()
  await forms.nth(0).getByRole('button',{name:'Expand',exact:true}).click()
  assert.equal(await forms.nth(0).getByRole('button',{name:'Expand',exact:true}).getAttribute('aria-pressed'),'true')
  await page.getByRole('button',{name:'Reset examples'}).click()
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth),true,'Mobile horizontal overflow')
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:'/tmp/lanark-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('button',{name:'Compare proposals',exact:true}).click()
  await page.screenshot({path:'/tmp/lanark-comparison.png',fullPage:true})
  await page.getByRole('button',{name:/All checks/}).click()
  await page.locator('#trace-condition-conflict summary').click()
  await page.locator('#trace-condition-conflict').getByRole('button',{name:'assessment',exact:true}).first().click()
  await page.locator('#source-assessment a').waitFor({state:'visible'})
  assert.equal(await page.locator('#source-assessment').getAttribute('open'),'')
  assert.equal(await page.locator('#source-assessment').isVisible(),true)
  await page.getByRole('button',{name:'Proposals',exact:true}).click()
  await page.emulateMedia({media:'print'})
  assert.equal(await page.locator('.refresh-note').isVisible(),true,'Print must retain hidden-tab refresh provenance')
  assert.equal(await page.locator('#trace-flood').isVisible(),true,'Print must retain unchanged checks')
  await page.pdf({path:'/tmp/lanark-print.pdf',format:'A4',printBackground:true})
  assert.deepEqual(errors,[])
  console.log('PASS: immediately visible inputs, work-type buttons, tabs, source links, comparison, invalid input, conflict, failed refresh, download, mobile layout, print all tabs, no browser exceptions')
} finally { await browser.close() }
