import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'

const baseUrl = process.env.WELCOME_BASE_URL ?? 'http://127.0.0.1:5173'
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--enable-unsafe-swiftshader'] })
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  const page = await context.newPage()
  const errors = []
  const consoleMessages = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => consoleMessages.push(`${message.type()}: ${message.text()}`))
  await page.goto(`${baseUrl}/welcome`)
  await page.getByTestId('welcome-screen').waitFor({ timeout: 10000 })
  await page.evaluate(() => document.fonts.ready)

  const start = page.locator('.welcome-actions').getByRole('link', { name: 'Assess a property', exact: true })
  assert.equal(await start.getAttribute('href'), '/projects/new')
  const scene = page.getByTestId('neighborhood-scene')
  await scene.waitFor()
  await page.waitForFunction(() => ['ready', 'fallback'].includes(document.querySelector('[data-testid="neighborhood-scene"]')?.getAttribute('data-render-state')))
  const sceneState = await scene.getAttribute('data-render-state')
  assert.equal(sceneState, 'ready', `Software WebGL should render the scene. Browser messages: ${consoleMessages.join(' | ')}`)
  const pause = page.getByRole('button', { name: /pause animation/i })
  assert.equal(await pause.isEnabled(), true)
  await pause.click()
  await page.getByRole('button', { name: /resume animation/i }).waitFor()
  const frozenYaw = await page.getByTestId('scene-drag-surface').getAttribute('data-camera-yaw')
  await page.waitForTimeout(350)
  assert.equal(await page.getByTestId('scene-drag-surface').getAttribute('data-camera-yaw'), frozenYaw, 'Pause should hold camera angle')
  await page.getByRole('button', { name: /resume animation/i }).click()
  await page.getByRole('button', { name: /pause animation/i }).waitFor()
  await page.waitForTimeout(700)
  const dragSurface = page.getByTestId('scene-drag-surface')
  const animatedYaw = Number(await dragSurface.getAttribute('data-camera-yaw'))
  assert.notEqual(animatedYaw, 38, 'Automatic orbit should move the camera')
  await page.getByRole('button', { name: 'Rotate left' }).waitFor()
  const controlState = page.getByTestId('scene-control-state')
  assert.equal(await controlState.getAttribute('data-yaw'), '38')
  await page.getByRole('button', { name: 'Rotate left' }).click()
  assert.notEqual(await controlState.getAttribute('data-yaw'), '38')
  await page.getByRole('button', { name: 'Zoom in' }).click()
  assert.notEqual(await controlState.getAttribute('data-zoom'), '1')
  await page.getByRole('button', { name: 'Reset view' }).click()
  assert.equal(await controlState.getAttribute('data-yaw'), '38')
  assert.equal(await controlState.getAttribute('data-zoom'), '1')
  assert.equal(await dragSurface.getAttribute('data-camera-yaw'), '38', 'Reset should clear accumulated orbit')
  for (let index = 0; index < 10; index += 1) {
    const zoomIn = page.getByRole('button', { name: 'Zoom in' })
    if (await zoomIn.isDisabled()) break
    await zoomIn.click()
  }
  assert.equal(await controlState.getAttribute('data-zoom'), '1.5', 'Zoom must stop at its upper bound')
  assert.equal(await page.getByRole('button', { name: 'Zoom in' }).isDisabled(), true)
  await page.getByRole('button', { name: 'Reset view' }).click()
  const box = await dragSurface.boundingBox()
  assert.ok(box)
  await page.mouse.move(box.x + box.width * 0.35, box.y + box.height * 0.5)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width * 0.7, box.y + box.height * 0.5, { steps: 8 })
  await page.mouse.up()
  assert.notEqual(await controlState.getAttribute('data-yaw'), '38', 'Mouse drag should rotate')
  await page.getByRole('button', { name: 'Reset view' }).click()
  await page.getByRole('button', { name: 'Rotate right' }).focus()
  await page.keyboard.press('Enter')
  assert.notEqual(await controlState.getAttribute('data-yaw'), '38', 'Keyboard should operate scene controls')
  await page.getByRole('button', { name: 'Reset view' }).click()
  await page.getByText(/illustrative neighborhood, not a model of your property/i).waitFor()
  await page.screenshot({ path: '/tmp/housing-welcome-desktop.png', fullPage: true })
  await page.screenshot({ path: '/tmp/housing-welcome-desktop-viewport.png' })

  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, '390px introduction must not overflow horizontally')
  assert.equal(await page.getByTestId('scene-drag-surface').evaluate(element => getComputedStyle(element).touchAction), 'pan-y', 'Touch drag must allow vertical page scroll')
  await page.screenshot({ path: '/tmp/housing-welcome-mobile.png', fullPage: true })
  await page.screenshot({ path: '/tmp/housing-welcome-mobile-viewport.png' })
  await page.setViewportSize({ width: 320, height: 780 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, '320px introduction must not overflow horizontally')
  await page.screenshot({ path: '/tmp/housing-welcome-320.png', fullPage: true })
  await page.screenshot({ path: '/tmp/housing-welcome-320-viewport.png' })

  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  await page.getByTestId('welcome-screen').waitFor()
  const reducedMotionPause = page.getByRole('button', { name: /motion reduced/i })
  await reducedMotionPause.waitFor()
  assert.equal(await reducedMotionPause.isDisabled(), true, 'Reduced motion should disable manual animation control')
  assert.equal(await reducedMotionPause.getAttribute('aria-pressed'), 'true', 'Reduced motion should keep the scene paused')
  await page.getByRole('button', { name: 'Rotate right' }).click()
  assert.notEqual(await page.getByTestId('scene-control-state').getAttribute('data-yaw'), '38', 'Reduced motion still allows manual rotation')
  await page.getByRole('button', { name: 'Reset view' }).click()
  assert.equal(await page.getByTestId('scene-drag-surface').getAttribute('data-camera-yaw'), '38')

  await page.locator('.welcome-actions').getByRole('link', { name: 'Assess a property', exact: true }).focus()
  await page.keyboard.press('Enter')
  await page.getByTestId('guided-workspace').waitFor()
  assert.deepEqual(errors, [], 'Introduction and project transition should not throw browser errors')
  console.log(`Welcome browser flow passed: desktop, mobile, reduced motion, keyboard CTA, and ${sceneState} scene`)
  await context.close()

  const touchContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  const touchPage = await touchContext.newPage()
  await touchPage.goto(`${baseUrl}/welcome`)
  await touchPage.waitForFunction(() => document.querySelector('[data-testid="neighborhood-scene"]')?.getAttribute('data-render-state') === 'ready')
  const touchSurface = touchPage.getByTestId('scene-drag-surface')
  const touchBox = await touchSurface.boundingBox()
  assert.ok(touchBox)
  const x = touchBox.x + touchBox.width * 0.35
  const y = touchBox.y + touchBox.height * 0.5
  const cdp = await touchContext.newCDPSession(touchPage)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 70, y }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  assert.notEqual(await touchPage.getByTestId('scene-control-state').getAttribute('data-yaw'), '38', 'Horizontal touch drag should rotate')
  await touchPage.evaluate(() => window.scrollTo(0, 0))
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y: y + 40 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y: y - 110 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await touchPage.waitForTimeout(300)
  assert.ok(await touchPage.evaluate(() => window.scrollY > 0), 'Vertical touch swipe over scene should scroll page')
  await touchContext.close()
  console.log('Mobile touch drag and vertical page scroll passed')

  // Force WebGL unavailable to verify the explicit, static illustration fallback.
  const fallbackContext = await browser.newContext({ viewport: { width: 1280, height: 900 } })
  const fallbackPage = await fallbackContext.newPage()
  await fallbackPage.addInitScript(() => {
    const getContext = HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext = function (type, ...args) {
      if (typeof type === 'string' && /webgl/i.test(type)) return null
      return getContext.call(this, type, ...args)
    }
  })
  await fallbackPage.goto(`${baseUrl}/welcome`)
  const fallbackScene = fallbackPage.getByTestId('neighborhood-scene')
  await fallbackPage.waitForFunction(() => document.querySelector('[data-testid="neighborhood-scene"]')?.getAttribute('data-render-state') === 'fallback')
  await fallbackPage.getByTestId('scene-fallback').waitFor()
  await fallbackPage.locator('.welcome-static-label').waitFor()
  assert.equal(await fallbackScene.getAttribute('data-render-state'), 'fallback')
  assert.equal(await fallbackPage.getByRole('button', { name: /animation/i }).count(), 0, 'Fallback should not present animation controls')
  assert.equal(await fallbackPage.getByRole('button', { name: 'Rotate left' }).isDisabled(), true)
  assert.equal(await fallbackPage.getByRole('button', { name: 'Reset view' }).isDisabled(), true)
  await fallbackPage.getByText('3D controls unavailable. Static illustration shown.').waitFor()
  await fallbackPage.screenshot({ path: '/tmp/housing-welcome-fallback.png', fullPage: true })
  console.log('Welcome forced WebGL-unavailable fallback passed')
  await fallbackContext.close()

  const lossContext = await browser.newContext({ viewport: { width: 1280, height: 900 } })
  const lossPage = await lossContext.newPage()
  await lossPage.goto(`${baseUrl}/welcome`)
  await lossPage.waitForFunction(() => document.querySelector('[data-testid="neighborhood-scene"]')?.getAttribute('data-render-state') === 'ready')
  await lossPage.locator('.welcome-canvas canvas').evaluate(canvas => { canvas.dataset.old = 'true'; canvas.dispatchEvent(new Event('webglcontextlost', { cancelable: true })) })
  await lossPage.waitForFunction(() => document.querySelector('.welcome-canvas canvas')?.getAttribute('data-old') !== 'true')
  await lossPage.waitForFunction(() => document.querySelector('[data-testid="neighborhood-scene"]')?.getAttribute('data-render-state') === 'ready')
  assert.equal(await lossPage.getByRole('button', { name: 'Rotate left' }).isEnabled(), true, 'Controls should recover after context loss')
  await lossContext.close()
  console.log('WebGL context-loss recovery passed')
} finally {
  await browser.close()
}
